symbol: XAUUSDm

timeframe: M1        # bar timeframe for features/decisions
lookback_bars: 200   # for indicators (ATR/RSI/vol)

action_interval_seconds: 5       # minimum seconds between LLM calls
new_bar_only: true               # call LLM only on new bar close

risk:
  risk_per_trade: 0.005          # 0.5% of equity
  sl_min_points: 200             # broker safety baseline; AI may set larger
  max_spread_points: 400
  contract_size: 100.0           # approximate contract size for gold (tune per symbol)

confirmations:
  enabled: true
  m5_trend: true
  m15_context: false
  atr_m1_bounds: [200, 8000]

exits:
  # Optional: kept for non-AI fallback; not used if AI manages exits

safety:
  daily_max_loss_pct: 5.0

sessions:
  enabled: true
  # Trading hours in broker time (HH:MM-HH:MM). Multiple ranges allowed.
  windows:
    - "00:05-23:55"

cooldowns:
  after_order_seconds: 20

persistence:
  db_path: data/trades.sqlite
  csv_path: data/trades.csv

ai:
  model: gemma-3-12b-it
  url: https://generativelanguage.googleapis.com/v1beta/models/gemma-3-12b-it:generateContent
  timeout: 8
  max_retries: 2

features:
  atr_period: 14
  rsi_period: 14
  vol_window: 20
  skew_window: 30
