symbol: XAUUSDm

timeframe: M1        # bar timeframe for features/decisions
lookback_bars: 200   # for indicators (ATR/RSI/vol)

action_interval_seconds: 5       # minimum seconds between LLM calls
new_bar_only: true               # call LLM only on new bar close

risk:
  max_spread_points: 300         # e.g., 30 pips if digits=3 (tune to broker)
  risk_per_trade: 0.005          # 0.5% of equity
  rr_min: 1.5                    # minimum risk-reward
  sl_min_points: 150             # avoid ultra-tight SLs
  sl_max_points: 4000            # cap SL
  contract_size: 100.0           # approximate contract size for gold (tune per symbol)

confirmations:
  enabled: true
  m5_trend: true
  m15_context: false
  atr_m1_bounds: [200, 8000]

exits:
  be_trigger_points: 80
  trail_min_points: 150

clamps:
  atr_mult: 3
  min_points: 150
  max_points: 6000     # was 3000; allow TP beyond min to reach RR>=1.5

safety:
  daily_max_loss_pct: 5.0

sessions:
  enabled: true
  # Trading hours in broker time (HH:MM-HH:MM). Multiple ranges allowed.
  windows:
    - "00:05-23:55"

cooldowns:
  after_order_seconds: 20

persistence:
  db_path: data/trades.sqlite
  csv_path: data/trades.csv

ai:
  model: gemma-3-12b-it
  url: https://generativelanguage.googleapis.com/v1beta/models/gemma-3-12b-it:generateContent
  timeout: 8
  max_retries: 2


features:
  atr_period: 14
  rsi_period: 14
  vol_window: 20
  skew_window: 30
